### ISSUE TITLE
Define tables data and uses

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/peopledepot#1]
### Overview
We need to define tables so that we can create an ERD for validation.

### Action Items
- [x] Review VRMS tables 0.3 & 0.4
- [x] Review HackforLA data stores
- [x] List tables needed
  - [x] Add fields
  - [x] Add accepted inputs
  - [x] indicate where joined or association tables go
- [ ] Review VRMS and other data stores to identify if we used everything and annotate why we did not use some things.  
   - [ ] Add document to resources

### Resources/Instructions
- issue where we have been writing out all the tables https://github.com/hackforla/CivicTechJobs/issues/13
#### VRMS
- [current VRMS data models](https://github.com/hackforla/VRMS/tree/development/backend/models)
- [VRMS 0.4 Minimum Viable Product (MVP) Requirement doc](https://docs.google.com/document/d/16VvC0fbaXsvEQkQaVSj8dG3wFEHgErbjJ6H3akSUoVM/edit#) - contains proposed data models

#### Civic Opportunity
- [repo with volunteer opportunity board post links and role descriptions](https://github.com/hackforla/civic-opportunity/tree/master/roles-1)

#### Civic Tech Jobs
- [Civic Tech Jobs Figma](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=1%3A6)
 
#### Hack for LA (hackforla.org) data storage
- [projects](https://github.com/hackforla/website/tree/gh-pages/_projects)
- program areas: 
- [communities of practice](https://github.com/hackforla/website/tree/gh-pages/_data/internal/communities)

#### users of role data
- hackforla.org
   - https://www.hackforla.org/projects/100-automations (Current Team)
   - https://www.hackforla.org/communities-of-practice
- civictechjobs.org
   - to provide generic details for each job post
   - to provide overview of roles to visitors
- VRMS
   - future TBD
- Guides
   - to be able to suggest guides for users

### Links to current versions of db

- [Spreadsheet](https://docs.google.com/spreadsheets/d/1x_zZ8JLS2hO-zG0jUocOJmX16jh-DF5dccrd_OEGNZ0/)   where we are listing all the table names and fields
- [Lucid chart image ERD](https://lucid.app/publicSegments/view/7531ed46-77d2-4b91-a09c-b18f9f210980/image.png)
- [lucid chart ERD](https://lucid.app/lucidchart/ac2f3e81-00d2-4257-b1fc-266d7f0a4cbe/view)

**Comment by ExperimentsInHonesty** [comment]
<details>
<summary>Project Table</summary>

projectname : Char/String
projectDescription : String
githubOrgId : number (8 characters)
githubPrimaryRepoId: number (9 characters)
githubOrgUrl : String URL
githubPrimaryUrl: String URL
currentProjectStatus: (see Status Table)
Hide: Boolean
location: string
createdDate: Date format
statusHistory: (see Project Status Records Table)
slackUrl: URLString
googleDriveUrl
googleDriveId
hflaWebsiteUrl: String URL (links to a specific page, such as https://www.hackforla.org/projects/100-automations)
partners: (see partner table)
programAreas: String (see program area table)
SDGs:
projectLeads: (see association table)
ProjectImageLogo: String
ProjectImageHero:
ProjectImageIcon: //a tiny image that is square for linking to the project from other sites)

</details>

**Comment by ExperimentsInHonesty** [comment]
table to review with Ava

<details>
<summary>User Table</summary>

nameFirst: String
nameLast: String
gmail: String (email validation)
preferedEmail:
createdDate:
UserStatus: (see User Status Table)
practiceAreaCurrent: (see Practice Area Table)
jobTitleCurrent: user’s current professional/non-HfLA job
practiceAreaTarget: (see Practice Area Table) - can choose multiple
jobTitleTarget: String

DesiredRoles user’s desired contributor roles at HfLA (structured and comes from the CivicTechJobs data) - Talk to Ava about it.

CurrentSkills user’s current skills they want to use as a volunteer
TargetSkills user’s target skills to acquire as a volunteer
LinkedinAccount user’s public linkedin profile URL
referredBy: (see Referrer Table)
firstAttended: Date
githubHandle: (make sure it does not include https://github.com/)
phone:
textingOk: Boolean
slackID: Number (specific number of chars)
isHflaGithubMember: Boolean
github2FA: Boolean
githubMembershipPublic: Boolean
availability: (see Brigade/GMT Time Bucket Table) This is translated into GMT on the way in. (see #13 (comment))
TimeZone: TimeZoneObj
Conduct: Boolean
GoogleOrgCheck: DateObj
SlackOrgCheck: DateObj
GitHubOrgCheck: DateObj
Last Modified: DateObj
Password: Hashed String
</details>

**Comment by ExperimentsInHonesty** [comment]
outstanding questions

practiceAreaCurrent: (see Practice Area Table)
jobTitleCurrent: user’s current professional/non-HfLA job
practiceAreaTarget: (see Practice Area Table) - can choose multiple

**Comment by Neecolaa** [comment]
ERD: https://lucid.app/publicSegments/view/7531ed46-77d2-4b91-a09c-b18f9f210980/image.png
How ERDs work / how to read one: https://www.lucidchart.com/pages/ER-diagram-symbols-and-meaning#section_1
![](https://d2slcw3kip6qmk.cloudfront.net/marketing/pages/chart/erd-symbols/ERD-Notation.PNG)

Implied many-to-many relationships are connected using a pale line. These fields are arrays of IDs, which can't be restricted in the same way that foreign keys can.

**Needs editing:** We have information for an Accomplishment table and an Accomplishments table. Currently, I've changed Accomplishment to Win on the ERD.

To-do:
Make table names consistent (some are singular while others are plural)
Make data types consistent
Make join table naming consisted (leaning towards join[table1]_[table2])

**Comment by ExperimentsInHonesty** [comment]
remaining items to talk to Ava about:
- [ ] time buckets vs hour by hour

**Comment by ExperimentsInHonesty** [comment]
Tables I still need to review

- Brigade/GMT Time Bucket Table
- Frequency Table
- SDGs Target
- Referrer Table
- Languages Join Table

**Comment by ExperimentsInHonesty** [comment]
Nicole - practice area
- [ ] see https://www.bls.gov/oes/current/oes_stru.htm
- [ ] find data
- [ ] create table structure table
- [ ] populate with the data

David
- [ ] export vrms data of job titles

Bonnie
- [ ] SDGs 
- [ ] annotating which tables I have created
- [ ] which tables I have populated

**Comment by ExperimentsInHonesty** [comment]
Review Alex's analysis and see if it informs how we should ask the questions or structure the database
https://github.com/hackforla/civic-opportunity/issues/139

**Comment by ExperimentsInHonesty** [comment]
Current Status of project
- Nicole
  - [ ] going to make the employment and wage statistics tables(employment categories and names tables) and show us something next time.
- David 
  - [ ] reviewed the info from Alex and determined we need data about change in employment status including (job they have now, job they get during or post hfla).  We will revisit this once Nicole creates the employment categories and name tables.  Also, demographic information would be helpful, we will add that on v2 or later.
- Bonnie
- [ ] SDGs 
- [ ] annotating which tables I have created
- [ ] which tables I have populated
- [ ] Make a check type tab based on this [page of the sheet](https://docs.google.com/spreadsheets/d/1x_zZ8JLS2hO-zG0jUocOJmX16jh-DF5dccrd_OEGNZ0/edit#gid=990760269)

**Comment by ExperimentsInHonesty** [comment]
add fields to people depot recording if people visisted CTJ before onboarding, after onboarding

**Comment by drubgrubby** [comment]
Nicole and David met on this day, February 27, 2022

- Added user_employment_change table to track jobs that people get while or after HfLA.
- Added table modern_job_title to match the soc job id to a modern job title.

@ExperimentsInHonesty, we have => 
Questions: 
- Are the users.practice_area_current and users.practice_area_target pulled from the soc tables? 
- Are the users.job_tittle_current and users.job_title_target free-entered or pulled from a table/drop-down? 
- Re: adding when they visit CTJ - Do we track when they first visit civic tech jobs? If so, we can use the date of their onboarding and the date they sign up for ctj to find out which they did first.

**Comment by Neecolaa** [comment]
This was our initial issue for planning the structure of the new database. There are times where I come back to this issue in order to help figure out why something is structured the way it is. 

That said, this issue can be closed after the still relevant data is brought to the wiki (if it's not already there). The current size label reflects the amount of time I believe it'll take to accomplish that.

**Comment by shmonks** [comment]
@Neecolaa - I'm creating an issue for updating the wiki. Once that's done, I wonder whether we should add that issue as a dependency to this one, move this to the Icebox (given your comment above, on Mar 24 2023), and then close once the wiki issue is completed?
