### ISSUE TITLE
Disable merge commit in repo

### ISSUE THREAD

**Issue by fyliu** [hackforla/peopledepot#11]
### Overview
For a clean repo source code history, it's best to NOT allow the default merge strategy.

### Action Items
- [ ] Jason or Nicole to ask for admin permissions to the repo so they can change the repo settings. This will also be required for adding github actions and repo secrets for deployment
- [ ] In the General tab in the github repo Settings page, uncheck Allow merge commits 
- [ ] Add process documentation on rebasing code before doing pull requests

### Resources/Instructions
- Squashing is the one to use most of the time. Use squash merge if the individual commit steps don't matter for the pull request. Use rebase merge if the individual commit steps need to be preserved.
- The problem with the default merge is it can contain hidden modifications. If the changes haven't been merged for sometime, there can be merge conflicts, and it becomes the merger's task to make the code changes to resolve the conflicts. This can be a way to introduce errors since the merger is making decisions on changes they might not understand completely. It's much better for the code author to do a rebase to the current head of the main repo and resolve any conflict themselves before doing the pull request.

**Comment by ExperimentsInHonesty** [comment]
we have unchecked the top box
![image](https://user-images.githubusercontent.com/37763229/156947026-028c137f-8f8f-4df2-8d2e-3be00c47f4f1.png)
