### ISSUE TITLE
Generate Wiki sidebar automatically

### ISSUE THREAD

**Issue by ethanstrominger** [hackforla/peopledepot#112]
Peopledepot Wiki sidebar is customized which makes it difficult to keep up to date.  Standard approach to Github Wikis does not have a custom sidebar.  Sidebar then will list each document and the sections.

**Comment by yoyoyojoe** [comment]
Hey Ethan, thanks for the suggestion. When you create an issue, can you follow the format of an `Issue Template`? They are intended to help put issues into context, make them easy to navigate, and pave the way for more shape and color on actionable next steps. In most cases, I think the `Blank Issue` option would work.
