### ISSUE TITLE
Clarify requirements in README.md or a separate document, using notes from discussion

### ISSUE THREAD

**Issue by ethanstrominger** [hackforla/peopledepot#114]
### Overview
Most issues describe table definition.  There are no issues describing the feature the tables are supporting.  This suggests having stories or features with technical issues within the story/feature.  zenhub is one tool that does that.  We also need to understand what Epics (broad goals) that the backend is trying to support for v1.  Is it to provide ability for non-VRMS applications to store in the same database as VRMS and thereby having a central database?  Are there any additional requirements?

### Action Items
- [ ] Discuss at meeting
- [ ] Determine next step

### Resources/Instructions
[Slack discussion between Ethan and Fang](https://github.com/hackforla/peopledepot/discussions/104)

**Comment by ExperimentsInHonesty** [comment]
VRMS has its own user stories.  We have enough information to build the People Depot application and then write user stories later when we are ready to make the APIs.  New issues will get created then.
