### ISSUE TITLE
Test Issue: How to properly create new issues

### ISSUE THREAD

**Issue by joey-ma** [hackforla/peopledepot#116]
Clicking on the `+` icon on the upper right corner of `New Issue Review` column to "Add a note to this column" will create a new "card" to the column.

Clicking on `...` and then "Convert note to issue" converts the note to issue, without needing to follow any desired issue template.

**Comment by yoyoyojoe** [comment]
To create a new issue, 
- please open a new issue by going to the `Issues` tab 
<img width="128" alt="image" src="https://user-images.githubusercontent.com/86270711/208037778-9af9a2b7-f5b9-4b22-9329-f5fa796af8f8.png">

- click on the green button `New Issue` 
<img width="98" alt="image" src="https://user-images.githubusercontent.com/86270711/208037737-c26ab96e-bfca-44cd-9f84-551127f3052f.png">

- and click on the green button `Get started` to the right of "Blank Issue", unless you have a particular type of request.
![image](https://user-images.githubusercontent.com/86270711/208038254-d4b0dcaf-f054-4bde-b4c1-99f997ecb8af.png)

**Comment by yoyoyojoe** [comment]
Tested that this "card" in the "New Issue Review" column (in Project Management view) can be removed there, but the issue remains open.

Note that the Issue Templates choices are not triggered.

**Comment by ExperimentsInHonesty** [comment]
@joey-ma do we need to keep this issue, or can we close it.  I am aware of the feature, do you want the instructions you have written to be added to a team wiki?

**Comment by joey-ma** [comment]
> @joey-ma do we need to keep this issue, or can we close it.  I am aware of the feature, do you want the instructions you have written to be added to a team wiki?

Hi! This was just to point out that there's a way to bypass the template, which could've been done unintentionally, but was strange to me. Maybe just let anyone interested in creating an issue know to use one of the issue templates?

Yeah I'm not against closing it 🙂
