### ISSUE TITLE
Set Up CRUD functionality for a Users Model

### ISSUE THREAD

**Issue by JasonEb** [hackforla/peopledepot#12]
### Overview
As a developer, I'd like to see a Users model and controller for CRUD functionality with a RESTful API controller. From Fang's discussions with Cynthia:

 _Start with user model without relations and add other models and relations when functionality requires them. Essentially, front end-driven. Add stuff when they're going to be used._

Requirements include database constraints, migration, model, model validations, testing, seeding, and a RESTFul controller for a json platform with Django. 

### Action Items
- [ ] User Database Constraints
- [ ] User Migrations
- [ ] User Model
- [ ] User Validations
- [ ] User Unit Tests
- [ ] User Seeding
- [ ] CRUD Controller
   - [ ] POST
   - [ ] GET, INDEX 
   - [ ] UPDATE
   - [ ] DELETE 
- [ ] Swagger Documentation 

### Resources/Instructions

[Cynthia's FYIs from Fang](https://github.com/hackforla/ops/issues/12#issuecomment-1030944807)

**Comment by ExperimentsInHonesty** [comment]
- #83
