### ISSUE TITLE
Create a no-review direct-commit docs branch for working on documentation

### ISSUE THREAD

**Issue by fyliu** [hackforla/peopledepot#120]
### Overview

As PeopleDepot document makers, sometimes it's too much overhead to go through the PR review process for even the smallest changes. Using the wiki would make sense except we also would like to keep code-related docs in the code repo to use with sphinx. We should create a docs branch in the main repo that allows the team to make changes directly in the code repo without going through the formal PR review process.

### Action Items

- [ ] do the following in a fork before replicating it in the main repo
  - [x] create a docs branch from the main branch
  - [x] make sure docs branch can be modified without PR
  - [ ] make some test changes directly in the docs branch and merge it into the main branch (via command line)
  - [ ] make test changes in main and merge it into the docs branch (via command line)
  - [ ] create gh-workflow/action to automate the process
    - [ ] should limit the merging to the doc directory only for the docs -> main direction
    - [ ] create ticket if something goes wrong
- [ ] do the above in the main repo
- [ ] document what this does and the setup required in case we/someone else needs it later

### Resources/Instructions

- stackoverflow: github: [allow service account to bypass branch protection rules](https://stackoverflow.com/questions/72026208/add-github-token-to-allow-specified-actors-to-bypass-required-pull-requests-or-a)
- how to: [modify a github file from the UI](https://coderefinery.github.io/github-without-command-line/creating-using-web/#step-3-modify-a-file)

### Discussion items

- Given:
  - We need to merge changes from the main branch into the docs branch for docs committed with code.
  - We need to merge changes from the docs branch into the main branch for changes made in the docs branch.

- Need to decide:
  - Should we make the docs branch the single source of truth for documentation rather than the main branch?

**Comment by fyliu** [comment]
I'm trying this on my fork to see if this is doable. So far, I found out that github.com doesn't allow non-PR merges. It is doable on the commandline and we can make a bash script into a gh-action.

There's already [github action that does no-PR merges](https://github.com/marketplace/actions/direct-merge) so we can either use it or extend it.

I'm looking at verifying that the branch changes are limited to the docs directory before merging.

**Comment by fyliu** [comment]
Actually, I'm looking at another action to do a rebase instead of a merge. It would keep the history linear. I just need to figure out the commands to do it the way we want.

Blockers: feasibility still looking good
ETA. I would say early January, holiday schedule means not much time to make progress.

**Comment by fyliu** [comment]
I'm leaving this alone for now although it seems important to have, to smooth things out for team members that want to contribute more documentation without the PR formality.

I need to switch to #52 since @AzaniaBG is busy with work.

**Comment by yoyoyojoe** [comment]
@fyliu no worries!

I do think PR reviews are meaningful, and if any particular documentation PR is taking a long time to be reviewed, that itself is also an indication that either the review should be prioritized or the documentation PR has room to be improved (lacks purpose, correctness, clarity, etc).

I believe a GHA workflow could be useful, but will also take up sometime. Although it'd take up less time than custom solutions, I'd suggest that this can be addressed by those who has a particular interest on this topic (Documentation, GitHub Actions, Developer Experience, or GitHub tools in genera, etc).

To those who are interested to work on this, please feel free to assign yourself to this issue and we can discuss further.

**Comment by fyliu** [comment]
@ethanstrominger The team is committed to the current process.
