### ISSUE TITLE
Set up linters on github to check PRs

### ISSUE THREAD

**Issue by fyliu** [hackforla/peopledepot#124]
### Overview
In the interest of all devs, we should set up a style checker on the github side. There's several cases of code in main with inconsistent formatting that could have been prevented by running linters before committing or pushing, like what pre-commit provides automatically.

### Action Items

- [x] setup pre-commit.ci

### Resources/Instructions
- as much as possible, run the same checks on ci as locally.

**Comment by ExperimentsInHonesty** [comment]
- https://github.com/hackforla/website/issues/3546#issuecomment-1432116661

**Comment by fyliu** [comment]
We discussed this and we would like to use super linter

**Comment by AzaniaBG** [comment]
Update: I have reviewed some documentation and have a few questions for @fyliu on implementation:
1. Do we only want this action to run on a PR to the `main` branch?
2. Do we only need the following checked?
* MD files
* Python
* black
* flake8

**Comment by fyliu** [comment]
1. Yes only on PRs to main

2. Preferably everything that pre-commit checks. This is in case someone didn't install pre-commit locally or if they bypassed the checks using --no-verify.

So
- Dockerfile
- Python 
- 

Actually, it might be easier to just use the pre-commit bot to do the checks. It's free for public repos. I have it set up in my fork and it runs in the PR. There's still some issue with at least one of the checks, so it's running but not fully working for me.

**Comment by fyliu** [comment]
@AzaniaBG I found a way to run the rest of the checks using the pre-commit service. See them run in this [demo PR](https://github.com/fyliu/peopledepot/pull/13)
<kbd>![2023-12-05 12 51 06 github com 16e34b4d0f55](https://github.com/hackforla/peopledepot/assets/1160105/69aca888-2e02-4d3d-b4f0-43cab1421461)</kbd>
<kbd>![2023-12-05 12 54 31 results pre-commit ci 09a38015d846](https://github.com/hackforla/peopledepot/assets/1160105/eac5657d-4072-437f-951a-c4785cf2b7f5)</kbd>

**Comment by AzaniaBG** [comment]
@fyliu, thanks for the update. Does that mean super-linter is not required here?

**Comment by fyliu** [comment]
Yes. I think we should just use pre-commit both in github and locally since they can both run using the same config file.

The only thing left in the pre-commit config that's runnable from github is pytest. That's probably a different issue since people have so many strategies to run it on github it probably takes time to figure out which one we should use.

**Comment by AzaniaBG** [comment]
@fyliu ~ Thanks, we can discuss setting up a new issue (per [your last comment](https://github.com/hackforla/peopledepot/issues/124#issuecomment-1841692425)) at today's meeting.

**Comment by fyliu** [comment]
@AzaniaBG it's basically [this](https://testdriven.io/blog/python-code-quality/#ci-pipeline:~:text=%2D%20name%3A%20Run%20tests%0A%20%20%20%20%20%20%20%20run%3A%20poetry%20run%20pytest). But it looks like we need to make the project runnable without docker for this type of GHA to work. I have an issue to [set it up using poetry](https://github.com/hackforla/peopledepot/issues/178) which is #178. 

@ethanstrominger got it to run and he's using another tool called [pur](https://github.com/alanhamlett/pip-update-requirements). I think it's still better to use poetry at this point. Its functionality includes dependency management and creating the virtual environment for running the project. It also lets us separate dev vs. production dependencies.

**Comment by fyliu** [comment]
I'm changing the issue to one using pre-commit.ci.

I didn't know about it at them time of creating this issues, and my thoughts were to run the same checks as the local pre-commit using something like superlinter. But it's pretty hard to hit all the same checks.

Recently, I was reading the Git DX book which mentioned pre-commit.ci and how to use it. It uses the same config file as the local pre-commit setup, so most of it just worked when I thought I was going to try it for fun. It was so easy and the checks are exactly the same as the local ones that it became clear that we should be using it. It's also faster than the competition.
