### ISSUE TITLE
Integrate cognito functionality into django user model

### ISSUE THREAD

**Issue by fyliu** [hackforla/peopledepot#13]
### Overview
We want to implement the user model in a way that allows the backend to use cognito authentication for users.

### Action Items
- [x] Follow the django cognito guide in the resources, using cognito token as username
- [ ] Maybe see if it can work with the VRMS client that talks to cognito
- [x] cleanup and documentation

### Resources/Instructions
- See the interaction diagram [here](https://djangostars.com/blog/bootstrap-django-app-with-cognito/). The frontend doesn't login to the backend. The frontend logs in to cognito, gets tokens, and uses a token to communicate with the backend. The backend has a separate connection with cognito to authenticate users.
- [VRMS cognito issue](https://github.com/hackforla/VRMS/issues/636)

**Comment by fyliu** [comment]
I implemented the way that's done in the djangostars tutorial. It might not be a robust implementation. For example, it download the jwks file on server launch. It might need to also periodically check that file to catch any new django users created after server launch. It's also only a dev setup. Right now, successful login redirects to localhost. I guess in real use the frontend will log in to cognito and get the access_token and keep it valid to access the API.

**Comment by JasonEb** [comment]
![image](https://user-images.githubusercontent.com/6300995/173976281-01b619fe-25f6-4661-b466-bcd1abc839da.png)
this seems like to be an issue .
