### ISSUE TITLE
Recruit for team members

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/peopledepot#132]
### Overview
We need to post our help wanted on each of the relevant open roles boards so that we can fill out the team

### Action Items
- [ ] Identify which roles
- [ ] Draft the post

#### Open Roles Boards
- [UI/UX - Design](https://github.com/hackforla/UI-UX/projects/3)
- [UI/UX - Research](https://github.com/hackforla/UI-UX/projects/2)
- [Data Science](https://github.com/hackforla/data-science/projects/2)
- [Engineering](https://github.com/hackforla/development/projects/2)
- [Ops](https://github.com/hackforla/ops/projects/1) 
- [Product Management](https://github.com/hackforla/product-management/projects/8)

**Comment by ExperimentsInHonesty** [comment]
# Posted on 2023-02-09
[Product Manager](https://github.com/hackforla/product-management/projects/8#card-88012903)
---
**Project Name**: People Depot

**About the Project**: PeopleDepot aims to provide a single source of truth as the backend infrastructure and data store for Hack for LA projects, including data about people, program areas, and projects. The goal is to serve as a repository of information for other infrastructure projects (e.g., VRMS, Hack for LA Website, Civic Tech Index, Tables, etc).

**Volunteer Opportunity**: Product Manager

**Duration**:  As long as possible

**Who to communicate your interest to**
- Slack channel link: #[peopple-depot](https://hackforla.slack.com/archives/C02PTACSRJQ)

[Read more about the project](https://github.com/hackforla/peopledepot#readme)

**Meeting Times**
- Thursday 4:00pm PST

**Comment by ExperimentsInHonesty** [comment]
# Posted on 2023-02-09
[Designer]()
---
**Project Name**: People Depot

**About the Project**: PeopleDepot aims to provide a single source of truth as the backend infrastructure and data store for Hack for LA projects, including data about people, program areas, and projects. The goal is to serve as a repository of information for other internal infrastructure projects (e.g., VRMS, Hack for LA Website, Civic Tech Index, Tables, etc.) 

**Volunteer Opportunity**: Designer for logo, website, marketing materials, etc.

**Duration**:  As long as possible

**Who to communicate your interest to**
- Slack channel link: #[peopple-depot](https://hackforla.slack.com/archives/C02PTACSRJQ)

[Read more about the project](https://github.com/hackforla/peopledepot#readme)

**Meeting Times**
- Thursday 4:00pm PST

**Comment by ExperimentsInHonesty** [comment]
We posted open roles, but have not had any takers.  What is our next step?

**Comment by shmonks** [comment]
@ExperimentsInHonesty 
- This issue is outdated and seems to have been superseded by #310 - ready to close?
