### ISSUE TITLE
Setup Figma

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/peopledepot#145]
### Overview
We need a figma team so that we can support designers who will work on the project

### Action Items
- [x] Setup figma using the email address of the project
- [x] add yourself and bonnie to it
  - [x] bonnie will show whoever is doing this issue how to make a team file
- [x] later we will add the team members to it that need it
- [ ] Add link to our figma in the wiki

### Resources/Instructions
- project email peopledepot@hackforla.org (log in via 1password)
- [People Depot Main Figma File](https://www.figma.com/files/team/1233067680023284399/PeopleDepot?fuid=775836858007206739)

**Comment by Kathleenfrancois** [comment]
(Figma link)<https://www.figma.com/files/team/1233067680023284399/PeopleDepot?fuid=1233067671757269789>
(Link to invite members)<https://www.figma.com/team_invite/redeem/xSIBXoVGWoyVhjSlJYxdYG>

**Comment by ExperimentsInHonesty** [comment]
Invite all the team members to the fima

**Comment by ExperimentsInHonesty** [comment]
This resource has been added to the wiki
