### ISSUE TITLE
Missing Permission Type

### ISSUE THREAD

**Issue by fyliu** [hackforla/peopledepot#147]
### Overview

PermissionType data in the [tables spreadsheet](https://docs.google.com/spreadsheets/d/1x_zZ8JLS2hO-zG0jUocOJmX16jh-DF5dccrd_OEGNZ0/edit#gid=1448710921) should include a default permission that has almost no permission, like "Unverified user" or "Pre-onboarded user".

### Action Items

- [ ] [team discussion?] decide on a name for the new permission type
- [ ] add a row to the spreadsheet for the name
- [ ] indicate that this is the default permission type
- [ ] move #24 out of ice box

### Resources/Instructions
[tables spreadsheet](https://docs.google.com/spreadsheets/d/1x_zZ8JLS2hO-zG0jUocOJmX16jh-DF5dccrd_OEGNZ0/edit#gid=1448710921)

### Discussion
Remember that anyone is free to sign up for the cognito account before onboarding and have a valid login to the PD backend. Right now, the lowest permission level is memberGeneral, which I assume has more permission than we want to give a pre-member. For example, we don't want to allow people to start joining projects before they accepted the terms and conditions.

**Comment by fyliu** [comment]
Ethan's work needs this level of no permission, where a registered user should have only public-level access until it's moved to memberGeneral.

**Comment by ExperimentsInHonesty** [comment]
We think we don't need another permission type because the user status and check type tables will end up being used in combination to restrict access.

Discussion participants
Fang
Bonnie
Shifra

**Comment by fyliu** [comment]
To clarify some more: The system would check that user status is "active" and that all the required checks are completed before allowing a user "member" level access.
