### ISSUE TITLE
Cleanup calendar invites in people depot email account.

### ISSUE THREAD

**Issue by bonniewolfe** [hackforla/peopledepot#179]
### Overview
We need to create a filter that archives meeting cancelation email notifications so that our inbox is more readable

#### Set up the Gmail account with the structure you need 
- [x] Open the Gmail account to create filter(s) in
- [x] Create the labels you need (see resources for list)
- [x] Go to the Setting>Filters and Blocked Addresses in your Gmail account by copying [this link](https://mail.google.com/mail/u/0/?tab=rm&ogbl#settings/filters) into your browser (if this takes you to another email address, use the instructions to get to `Filters and Blocked Addresses` through the settings tab of the email you want to use)

#### Create your filter(s)
- [x] Click on 'Create a new filter'
- [x] Next to 'Has the words', enter the desired query (see below for query to use)
- [x] Check the 'Has attachment box'
- [x] Click 'Create filter'
- [x] Check the 'Apply the label' box 
  - [x] Choose the appropriate label to automatically sort incoming event response messages
- [x] Check the 'Skip the Inbox (Archive it)' box to move response messages out of your inbox. (You can still view them later)
- [x] Check 'Also apply filter to X matching conversations.'
- [x] Click 'Create filter'
- [x] Repeat for each filter needed

#### Labels (when creating the CI labels, nest them under Calendar Invites)
- [x] Calendar Invites
   - [x] CI: Accepted
   - [x] CI: Canceled
   - [x] #192
   - [x] CI: Tentative

#### Get to Filter tab
- [x] Click on the Settings gear icon in the top right corner
- [x] Click on 'see all settings'
- [x] Click on the 'Filters and Blocked Addresses' tab

#### Queries
   - [x] Accepted
```
invite.ics OR invite.vcs AND Accepted
```
   - [x] Canceled
```
invite.ics OR invite.vcs AND Canceled
```
   - [x] Declined
```
invite.ics OR invite.vcs AND Declined
```
   - [x] Tentative
```
invite.ics OR invite.vcs AND Tentative
```

**Comment by Kathleenfrancois** [comment]
Issue #192 was created by accident.
