### ISSUE TITLE
ER: Consolidating Technology, Tool, Language tables into one table.

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/peopledepot#202]
### Emergent Requirement - Problem
We need to combine the technology, tools and languages into one table that has a FK of type.  The type would come from a new table that would have the following values:
- tool
- technology
- language (cannot be edited manually, only can be updated by GitHub API call to find project languages.

The new type table will be stack_element_type

### Issue you discovered this emergent requirement in
- #148
- #150 

### Date discovered 
2023-09-18

### Did you have to do something temporarily
- [ ] YES
- [ ] NO

### Who was involved
@Neecolaa @PlantGirlCodes @ExperimentsInHonesty 

### What happens if this is not addressed
its inefficient and we will have to write sophisticated sql queries to make sure that the values aren't classified under a different category. 

### Resources
- #54
- #64
- #39 
- #40 
- https://www.hackforla.org/projects-check/ (to see which projects have what data in tools, technology, language) - hack for la website team uses this page to check to see if projects have miscategorized technologies and tools.

### Recommended Action Items
- [x] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]

- [x] close the issue for any tables and xref's not yet created
- [ ] pick one of the created tables and amend so that it can accept all the TTLs and rename either TTL, LTT, TLT
   - #204 technology is being amended
- [ ] pick one of the xref tables to use and amend
   - #205  neither xref table was created yet, so we made a new create table issue instead
- [ ] create new type table
   - #206

**Comment by Neecolaa** [comment]
Created the table issues for this ER
#206 
#204 
#205 
There are some fields I was unsure about, so I gave them all draft labels for now. 

I went with the name ttl so l(lower-case L) /I(upper-case i) confusion would be less likely. TTL does stand for "Time to live" though, so maybe we should switch it to tlt? Or a grouping word if we think of one.

**Comment by Neecolaa** [comment]
- Updated all the issues to stack_element as agreed on during today's team meeting. #103 
- Closed the xref issues w/ a comment linking the new xref table. 
- Added links to the table issues to the body of this ER issue.
