### ISSUE TITLE
Create Table: stack_element_type

### ISSUE THREAD

**Issue by Neecolaa** [hackforla/peopledepot#206]
### Dependency
 - ~#207~ Completed for this table

### Overview

We need to create the ttl_type table so that we can update a shared data store across hackforla.org, vrms, civictechjobs, and tables (onboarding) project.

#### Details

A table and a model are the same thing

### Action Items
- [x] create a single model in Django (defining schema)
- [ ] write a test for the relationships this model will have with other models (e.g., creating a user and assigning them a set of permissions on a project).
- [x] write an API end point
- [x] write API unit tests
- [x] document the endpoint

### Resources/Instructions

- See [People Depot Resources wiki page](https://github.com/hackforla/peopledepot/wiki/Resources-and-Links) for links
  - [ERD](https://lucid.app/lucidchart/ac2f3e81-00d2-4257-b1fc-266d7f0a4cbe/view?page=0_0#)
  - [Table and Field Definitions](https://docs.google.com/spreadsheets/d/1x_zZ8JLS2hO-zG0jUocOJmX16jh-DF5dccrd_OEGNZ0/edit#gid=1228509670)
  - API Endpoint
- See the [wiki page](https://github.com/hackforla/peopledepot/wiki/Create-Table-issues-data-gathering-workflow) for instructions.

### Description

Indicating whether a record in the ttl table is a technology, tool, or language (and possibly other types in the future).

### Data Fields

1. New fields
    - [ ] (PK) id - int - Record Id
    - [ ] name - varchar
    - [ ] description - varchar 

### Associated Tables

1. New associations
   - [ ] stack_element (one-to-many)

**Comment by AzaniaBG** [comment]
Availability:
Tuesday: 12:45 - 1:45 PM
Wednesday: 8 - 9 AM
Thursday: 10:30 - 12:30 PM
Note: I added a link to the ERD in this issue (under Resources/Instructions)

**Comment by AzaniaBG** [comment]
In addition to tasks above the following were done so far:
* Register model 
* Create a Serializer
* Create a ViewSet
* Register the API endpoint (ViewSet)

**Comment by AzaniaBG** [comment]
I need help with this, and posted my issue in Slack earlier this week.

**Comment by AzaniaBG** [comment]
I submitted a PR (#220) and requested @fyliu's review on 10/22
Questions:
* what's the best way to test that the table is working properly?

**Comment by AzaniaBG** [comment]
Working on the requested changes - availability:
11/3: 10 AM - 12 PM
11/6: 10 AM - 12 PM

**Comment by AzaniaBG** [comment]
Working on requested changes. I will follow up with Fang if I can't figure out the issues I'm facing.
Availability:
11/11: 9 AM - 12 PM
11/12: 9 AM - 12 PM

**Comment by AzaniaBG** [comment]
I re-requested review today.
