### ISSUE TITLE
Create Table: user permission

### ISSUE THREAD

**Issue by fyliu** [hackforla/peopledepot#22]
### Dependency

 - #148

### Overview

We need to create the user permission table so that we can update a shared data store across hackforla.org, vrms, civictechjobs, and tables (onboarding) project.

#### Details
A table and a model are the same thing

### Action Items
- [x] identify if table has a description (see spreadsheet under Resources)
  - [ ] if not, reach out to PD leads
- [x] identify and document (below) what the **data fields** are and make sure the ERD and spreadsheets match (see Resources)
- [x] identify and document  (below) what **other tables are associated** and make sure the ERD and spreadsheets match (see Resources)
- [ ] create a single model in Django (defining schema)
- [ ] Write a test for the relationships this model will have with other models (e.g., creating a user and assigning them a set of permissions on a project)
- [ ] Write an API end point
- [ ] write API unit tests
- [ ] Document the endpoint in Swagger

### Resources/Instructions
- See [People Depot Resources wiki page](https://github.com/hackforla/peopledepot/wiki/Resources-and-Links) for links

#### Description
- User permissions for project, brigade, etc.

#### Data Fields
1. Copied from spreadsheet and checked off according to ERD. Data fields are bolded and relation fields are not. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)
   - [x] PK - id - int - Record Id
   - [x] FK - user_id - int - Record Id
   - [x] FK - project_id - int - Record Id
   - [x] FK - permission_type_id - int
   - [x] FK - practice_area_id - int - Record Id
   - [x] granted - timestamp
   - [x] ended - timestamp

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - created_by - int
   - updated_by - int

#### Associated Tables
1. Copied from spreadsheet and checked off according to ERD (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)
   - [x] permission_type (many-to-one)
   - [x] practice_area (many-to-one)
   - [x] project (many-to-one)
   - [x] practice_area_id (many-to-one)
   - [x] user (many-to-one)

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

#### Swagger Endpoint Link
-

**Comment by Neecolaa** [comment]
created_by and updated_by are both foreign keys containing user ids. If a permission isn't what it should be, we can use these values to figure out who to ask. I've just added the fields to the spreadsheet.

**Comment by fyliu** [comment]
This table is really a "membership" relationship xref table between user and project, with associated roles and permissions attributes. Should we change the name to "membership" or "member" or similar?

**Comment by joshuayhwu** [comment]
```
class Permission(AbstractBaseModel):
	"""
	Permission
	"""
	id = models.IntegerField(primary_key=True)
	user_id = models.ForeignKey(User, on_delete=models.CASCADE)
	project_Id = models.ForeignKey(Project, on_delete=models.CASCADE)
	permission_type = models.ForeignKey(Project, on_delete=models.CASCADE)
	granted = models.DateTimeField()
	ended = models.DateTimeField()


	def __str__(self): 
		return f"{self.name}" 

```

**Comment by fyliu** [comment]
Update for the record: according to @ExperimentsInHonesty during a meeting, this is not a membership junction table between user and project. It's a property relating to user. There's an optional reference to project if it makes sense to have it. Where it doesn't make sense is for a brigade admin role which has permission to all projects under that brigade.

Question: should there be a reference to brigade here? I'm thinking yes and it should be optional. A global admin would have permission to all brigades the same way that a brigade admin relates to projects.

**Comment by fyliu** [comment]
This issue requires some research into the best way to implement permissions in django. 

- [ ] Does django come with one? 
  - [ ] Does it fit our use well? 
  - [ ] Can we make it work for us? 
- [ ] What 3rd party plugins/apps are there and do any of them already do what we need or can be made to work? 
- [ ] Do we need to implement our own solution?

**Comment by Neecolaa** [comment]
ERD/SS To-do:
replace role_id with practice_area_id
- [ ] on the ERD
- [ ] on the fields tab of the spreadsheet

remove relationship between role and permission tables
- [ ] on the ERD
- [ ] on the spreadsheet
- [ ] on this issue

add relationship between practice_area and permission tables
- [ ] on the ERD
- [ ] on the spreadsheet
- [ ] on this issue

Discussion for these changes happened here: https://github.com/hackforla/peopledepot/discussions/170
