### ISSUE TITLE
local deployment without docker

### ISSUE THREAD

**Issue by fyliu** [hackforla/peopledepot#240]
### Overview

We would like to support local deployment of the backend without the use of docker. This would support a greater number of developers who are more comfortable running things in virtual environments.

### Action Items

- [ ] set up the project to run by itself
- [ ] document how to run it

**Comment by ExperimentsInHonesty** [comment]
@ethanstrominger Fang made this issue for you.
I see the following PRs that should probably be associated with it.   Let's talk about how we want to get changes.
- https://github.com/hackforla/peopledepot/pull/243
- https://github.com/hackforla/peopledepot/pull/245
