### ISSUE TITLE
User login page (KB requirement)

### ISSUE THREAD

**Issue by fyliu** [hackforla/peopledepot#241]
### Overview

We need to implement the ability for users to login directly to the PD backend to support KB functions.

Description is based on work @ethanstrominger already did in a branch.

### Action Items

- [ ] add a login page with the ability to authenticate with cognito

### Resources/Instructions

- [django-allauth](https://allauth.org) is a package that allows connecting to cognito, among many other authentication authorities.

**Comment by fyliu** [comment]
@ethanstrominger already has this working.

There's a security feature (client_secret) that needed to be disabled because it was difficult to make it work. Right now it runs fine without using `client_secret`. Will split that into a separate issue.

**Comment by ExperimentsInHonesty** [comment]
I added the milestone initial setup.

**Comment by ExperimentsInHonesty** [comment]
@fyliu I added the milestone initial setup. Can this issue be closed?

**Comment by fyliu** [comment]
@ExperimentsInHonesty this is an issue I created to attempt to describe some of @ethanstrominger 's code. I'm not sure if any of it is correct. We should ask Ethan.

**Comment by fyliu** [comment]
I'm not sure what the status of this issue is since the PR #234 is closed.
@ethanstrominger is this issue still going to be implemented?
