### ISSUE TITLE
Build issue: docker fails when trying to install postgres 13+225

### ISSUE THREAD

**Issue by ethanstrominger** [hackforla/peopledepot#262]
### Overview

As a developer, I want to be able to deploy docker without any fatal errors.

### Solution
Remove the line that installs postgres.  It may not be needed.  Otherwise, update 13+225 to an appropiate value.

**Comment by fyliu** [comment]
Just for reference, @freaky4wrld used this solution in his PR.

```
-  postgresql=13+225 \
+  postgresql=13+225+deb11u1 \
```

**Comment by fyliu** [comment]
@ethanstrominger said removing this dependency also works, and indeed it worked for me. In fact, it looks like `graphviz` is the only required dependency.

**Comment by fyliu** [comment]
Fixed in 37f300562843b503deead4c6c8c85725b0e46289
There's also a PR which removes it.
