### ISSUE TITLE
Create milestones and labels for PeopleDepot

### ISSUE THREAD

**Issue by fyliu** [hackforla/peopledepot#34]
### Overview
As a project that wishes to operate effectively, we need to create structure in the form of milestones and labels to 

### Action Items

- [ ] come up with labels and milestones
- [ ] setup labels and milestones

### Resources

Potential labels or milestones
- application security
  - SAST (code climate or similar tools)
  - dependency checking (github Dependabot, Snyk)
  - OWASP top 10
- code quality
  - test cases
  - code formatter
  - code lint
- project infrastructure/automation
  - create deployment-ready dockerfile
  - setup pre-commit hook for linting, etc.
  - setup github workflows/actions
    - code linting
    - API client generation
    - build and update container registry
- documentation
  - API doc (think unit testing)
    - resource descriptions
    - endpoint descriptions
    - examples
    - input field hints
  - Reference (think integration testing)
    - descriptions of system components and how they work with (relate to) other components
  - how-to guides (think end to end testing)
    - how to add a new data table/model
  - tutorials (think concrete example)
    - set up and use PeopleDepot from a simple react frontend using the API client library

**Comment by ExperimentsInHonesty** [comment]
drafting general structure notes here https://github.com/hackforla/website/wiki/Labels-and-Milestones.  will need to update from the changes i made today

**Comment by ExperimentsInHonesty** [comment]
We need to review the[ label audit spreadsheet](https://docs.google.com/spreadsheets/d/1kQ-0C-GVrNdrP-5GRwjbXltV73LFUzbJzB1rrQQVTnI/edit#gid=0) and add notes about any label types into the wiki page https://github.com/hackforla/website/wiki/Labels-and-Milestones.

**Comment by ExperimentsInHonesty** [comment]
Add a section on this page for each of the following label types

Complexity
frequency
Misc
Misc.
missing
p-feature
PII
role
size
work type

**Comment by Kathleenfrancois** [comment]
Added label types to  [wiki page](https://github.com/hackforla/website/wiki/Labels-and-Milestones)
