### ISSUE TITLE
GHA to set role and complexity from labels

### ISSUE THREAD

**Issue by fyliu** [hackforla/peopledepot#352]
### Overview

We need to sync the Role and Complexity issue fields from the labels so they show up correctly in the project board's corresponding tabs.

### Action Items

- [ ] create a GHA to listen to add label events and set or unset the issue fields

**Comment by shmonks** [comment]
@fyliu Hey Fang, just to let you know that Bonnie is working on an org-wide standardized formatting for labels, at which point I'll go through the project board and make all necessary changes, including to issue templates. This might affect your issue #352? I'm not sure which project board tabs you're referring to in the 'Overview' section above.

**Comment by fyliu** [comment]
@shmonks Thanks for the head up! That's a great step to be taking!

This shouldn't be affected. Just updating the names should be good.

This issue is to create GitHub Actions that reads issue labels and sets the corresponding Project fields. It's automating what I've been doing manually so that the "Prioritized Backlog", "Ready for", and "Assignee" tabs will work correctly.
