### ISSUE TITLE
Create Table: skills (formerly role) :smile: 

### ISSUE THREAD

**Issue by Neecolaa** [hackforla/peopledepot#38]
### Overview

We need to create the role table so that we can update a shared data store across hackforla.org, vrms, civictechjobs, and tables (onboarding) project.

#### Details

A table and a model are the same thing

### Action Items
- [x] add issue link to [the tables tab of the spreadsheet](https://docs.google.com/spreadsheets/d/1x_zZ8JLS2hO-zG0jUocOJmX16jh-DF5dccrd_OEGNZ0/edit#gid=1228509670)
- [x] identify and document table description (see spreadsheet under Resources)
- [x] compare and check off the data fields (below) against the ERD. Note any fields in the ERD that's missing from the list. (see Resources)
- [x] compare the check off associated tables (below) against the ERD. Note any associated tables in the ERD that's missing from the list (see Resources)
- [ ] create a single model in Django (defining schema)
- [ ] write a test for the relationships this model will have with other models (e.g., creating a user and assigning them a set of permissions on a project).
- [ ] write an API end point
- [ ] write API unit tests
- [ ] document the endpoint

### Resources/Instructions

- See [People Depot Resources wiki page](https://github.com/hackforla/peopledepot/wiki/Resources-and-Links) for links
  - ERD
  - Table and Field Definitions
  - API Endpoint
- See the [wiki page](https://github.com/hackforla/peopledepot/wiki/Create-Table-issues-data-gathering-workflow) for instructions.

### Description

Dictionary of brigade roles.

### Data Fields

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)
   - [x] (PK) id - int
   - [x] name - varchar
   - [x] description - textfield
   - [ ] responsibilities - varchar
   - [ ] qualifications - varchar
   - [ ] created - timestamp
   - [ ] updated - timestamp

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - [ ] created_date - timestamp
   - [ ] last_updated - timestamp

### Associated Tables

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)
   - [x] permission (one-to-many)
   - [x] permission_history (one-to-many)
   - [x] recurring_event (many-to-many array of IDs)
   - [x] user (many-to-many array of IDs)
   - [x] win (many-to-many array of IDs)

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

**Comment by Neecolaa** [comment]
We currently have a few different labels for the record created and record updated fields.

Creation records have:
- created
- created_date
- created_at

Update records have:
- updated
- last_updated
- updated_at

**Comment by ExperimentsInHonesty** [comment]
We need to talk to CTJ and VRMS (mostly CTJ) to see how they plan to use this data.

**Comment by fyliu** [comment]
Edited description field to be textfield in django

**Comment by fyliu** [comment]
> we are removing the
> 
> * responsibilities - varchar
> * qualifications - varchar
>   from this table.  See ER

@bonniewolfe the ERD is not updated to reflect this removal. Is this table good to work on with this change? Or do we not need this table anymore? 

This "role" is talking about the brigade roles, like the table description says. It looks like the skills matrix discussion started here and got moved to a separate table.

What would be some example roles? Is it supposed to be like one of the open roles postings? I assume each posting would create a separate role entry. If this table only has a name and description, would it need to be paired (db reference) with a skills matrix entry so that the software can do the first step in matching roles and candidates?
