### ISSUE TITLE
Stakeholder engagement: which API documentation UI to use?

### ISSUE THREAD

**Issue by shmonks** [hackforla/peopledepot#388]
### Overview

We need to get feedback from stakeholders about preferred form of API documentation, following Fang's research indicating pros and cons of two main options: Swagger and Redoc

### Action Items

- [x] Create draft of slide deck 
- [x] Review
- [x] Send link to Bonnie for feedback
- [x] Send message to VRMS (and CTJ?) PMs, asking if we can join one of their team meetings to talk about it, with link to version of slide deck saved to local drive
- [x] Record stakeholder feedback in a comment below

### Resources/Instructions

- #239 
- #381 
- https://github.com/hackforla/peopledepot/issues/103#issuecomment-2359579182
- Completed slide deck: https://docs.google.com/presentation/d/1ugoZ33ptZTdiAjDZpd5bd7FrLQbIVcOPVjP4GkJ0EiE/edit#slide=id.g1443c52839c_0_2

**Comment by shmonks** [comment]
Hi @vanessaavviles - please consider the following questions and add an update below:
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by vanessaavviles** [comment]
Fang could not make the meeting this past tuesday, so we will work on going through the presentation all 3 of us next tuesday's meeting and have it ready to show the team thursday of next week.

**Comment by vanessaavviles** [comment]
Finished presentation, Fang and I decided it would be best for the 3 of us to look it over together for one last glance before presenting it at all teams.

**Comment by shmonks** [comment]
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?" **We met this morning and ran through final changes and cleanup, which Vanessa will implement before finalization**
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?" **Next week**
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by vanessaavviles** [comment]
Revised PP with sarah and fang, need to make a few changes to the presentation before revising again. After that, PP should be ready to demonstrate to team.

**Comment by shmonks** [comment]
- Slide deck now available for review: https://docs.google.com/presentation/d/1ugoZ33ptZTdiAjDZpd5bd7FrLQbIVcOPVjP4GkJ0EiE/edit#slide=id.g1443c52839c_0_2

**Comment by shmonks** [comment]
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?" **Slide deck completed and ready for review:** https://docs.google.com/presentation/d/1ugoZ33ptZTdiAjDZpd5bd7FrLQbIVcOPVjP4GkJ0EiE/edit#slide=id.g1443c52839c_0_2
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by ExperimentsInHonesty** [comment]
This was presented in the people depot team meeting tonight.

- Ethan looked at it and said whatever Fang recommends is fine
- Bonnie looked at it and said redocs is her recommendation
- Fang recommends redocs

Ask the CTJ and VRMS tech leads for their recommendation after seeing the presentation

**Comment by shmonks** [comment]
Remember to update the following issues with feedback once we have it:
- #377 
- #426

**Comment by shmonks** [comment]
Stakeholder feedback:
- Website team and CTJ prefer Redoc
- VRMS prefer Swagger
