### ISSUE TITLE
Create Table: technology

### ISSUE THREAD

**Issue by Neecolaa** [hackforla/peopledepot#39]
### Overview

We need to create the technology table so that we can update a shared data store across hackforla.org, vrms, civictechjobs, and tables (onboarding) project.

#### Details

A table and a model are the same thing

### Action Items

- [x] add issue link to [the tables tab of the spreadsheet](https://docs.google.com/spreadsheets/d/1x_zZ8JLS2hO-zG0jUocOJmX16jh-DF5dccrd_OEGNZ0/edit#gid=1228509670)
- [x] identify and document table description (see spreadsheet under Resources)
- [x] compare and check off the data fields (below) against the ERD. Note any fields in the ERD that's missing from the list. (see Resources)
  - [ ] Review and correct discrepancies 
- [x] compare the check off associated tables (below) against the ERD. Note any associated tables in the ERD that's missing from the list (see Resources)
- [ ] create a single model in Django (defining schema)
- [ ] write a test for the relationships this model will have with other models (e.g., creating a user and assigning them a set of permissions on a project).
- [ ] write an API end point
- [ ] write API unit tests
- [ ] document the endpoint
- [ ] Release #40 from ice box

### Resources/Instructions

- See [People Depot Resources wiki page](https://github.com/hackforla/peopledepot/wiki/Resources-and-Links) for links
  - ERD
  - Table and Field Definitions
  - API Endpoint
- See the [wiki page](https://github.com/hackforla/peopledepot/wiki/Create-Table-issues-data-gathering-workflow) for instructions.

### Description

Dictionary of technologies used in projects

### Data Fields

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)
   - [x] (PK) id - int - Record Id
   - [x] name - varchar
   - [x] description - textfield
   - [x] url - url varchar
   - [x] logo - url varchar
   - [x] updated - timestamp
   - [x] active - boolean

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - last_updated - timestamp

### Associated Tables

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)
   - [x] project_technology_xref (one-to-many)

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

**Comment by joshuayhwu** [comment]
```
class Technology(AbstractBaseModel):
	"""
	Technology
	"""
	id = models.IntegerField(primary_key=True)
	name = models.CharField(max_length=255)
	description = models.CharField(max_length=255)
	url = models.URLField(blank=True) 
	logo = models.URLField(blank=True) 
	last_updated = models.DateTimeField()
	active = models.BooleanField()


	def __str__(self): 
		return f"{self.name}" 

```

**Comment by fyliu** [comment]
Updated description field to be textfield in django

**Comment by ExperimentsInHonesty** [comment]
Hi Brenda, 

We are looking at your issue because its in the questions and review column.  We don't know what your question is.  And when we looked at your PRs we are a little more confused.

**Comment by ExperimentsInHonesty** [comment]
PR ready for next review #175
