### ISSUE TITLE
Create Table: project_technology_xref

### ISSUE THREAD

**Issue by Neecolaa** [hackforla/peopledepot#40]
### Dependency

 - #39

### Overview

We need to create the project_technology_xref table so that we can update a shared data store across hackforla.org, vrms, civictechjobs, and tables (onboarding) project.

#### Details

A table and a model are the same thing

### Action Items

- [x] add issue link to [the tables tab of the spreadsheet](https://docs.google.com/spreadsheets/d/1x_zZ8JLS2hO-zG0jUocOJmX16jh-DF5dccrd_OEGNZ0/edit#gid=1228509670)
- [x] identify and document table description (see spreadsheet under Resources)
- [x] compare and check off the data fields (below) against the ERD. Note any fields in the ERD that's missing from the list. (see Resources)
  - [ ] Review and correct discrepancies 
- [x] compare the check off associated tables (below) against the ERD. Note any associated tables in the ERD that's missing from the list (see Resources)
- [ ] create a single model in Django (defining schema)
- [ ] write a test for the relationships this model will have with other models (e.g., creating a user and assigning them a set of permissions on a project).
- [ ] write an API end point
- [ ] write API unit tests
- [ ] document the endpoint

### Resources/Instructions

- See [People Depot Resources wiki page](https://github.com/hackforla/peopledepot/wiki/Resources-and-Links) for links
  - ERD
  - Table and Field Definitions
  - API Endpoint
- See the [wiki page](https://github.com/hackforla/peopledepot/wiki/Create-Table-issues-data-gathering-workflow) for instructions.

### Description

Join table: links project with technology

### Data Fields

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)
   - [x] (PK) id - int - Record Id
   - [x] (FK) project_id - int - id of project linked to technology
   - [x] (FK) technology_id - int - id of technology linked to project
   - [ ] created - timestamp - When we started using this technology on this project
   - [ ] ended - timestamp - When we stopped using this technology on this project

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - created_date - timestamp
   - ended_date - timestamp

### Associated Tables

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)
   - [x] project (many-to-one)
   - [x] technology (many-to-one)

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

**Comment by fyliu** [comment]
This issue is better done after the technology table is created since it references it.

**Comment by fyliu** [comment]
This is just a normal join table. It looks ready to be worked on once the dependencies are met.

**Comment by Neecolaa** [comment]
- This table is being replaced by #205
