### ISSUE TITLE
Create Table: Event

### ISSUE THREAD

**Issue by fyliu** [hackforla/peopledepot#47]
### Overview

We need to create the event table so that we can update a shared data store across hackforla.org, vrms, civictechjobs, and tables (onboarding) project.

#### Details

A table and a model are the same thing

### Action Items

- [ ] identify and document table description (see spreadsheet under Resources)
  - [ ] if not, reach out to PD leads
- [ ] compare and check off the data fields (below) against the ERD. Note any fields in the ERD that's missing from the list. (see Resources)
- [ ] compare the check off associated tables (below) against the ERD. Note any associated tables in the ERD that's missing from the list (see Resources)
- [ ] create a single model in Django (defining schema)
- [ ] write a test for the relationships this model will have with other models (e.g., creating a user and assigning them a set of permissions on a project).
- [ ] write an API end point
- [ ] write API unit tests
- [ ] document the endpoint

### Resources/Instructions

- See [People Depot Resources wiki page](https://github.com/hackforla/peopledepot/wiki/Resources-and-Links) for links
  - ERD
  - Table and Field Definitions
  - API Endpoint
- See the [wiki page](https://github.com/hackforla/peopledepot/wiki/Create-Table-issues-data-gathering-workflow) for instructions.

### Description

Specific, one-time event

### Data Fields

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)
   - [x] (PK) id - int - Record Id
   - [x] (FK) project_id - int - Record Id
   - [x] description - varchar
   - [x] video_conference_url - url varchar - event’s Zoom/Google Meet/etc. Link (uses default link from recurring event and can be changed)
   - [x] (FK) location_id - int - Record Id
   - [x] alt_location_name - varchar
   - [x] alt_address1 - varchar
   - [x] alt_address2 - varchar
   - [x] alt_location_city - varchar
   - [x] alt_location_state - varchar(2)
   - [x] alt_location_zip - varchar
   - [x] start_date_time - timestamp - Contains both the day and time of the meeting
   - [x] duration_in_min - int
   - [x] (FK) recurring_event_id - int - Record Id
   - [x] created - timestamp
   - [x] check_in_ready - boolean - script runs every 15 min to identify which events are ready to be checked into

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - [name] - [type]

### Associated Tables

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)
   - [x] check_in (one-to-many)
   - [x] location (many-to-one)
   - [x] project (many-to-one)
   - [x] recurring_event (many-to-one)
   - [x] event_history (implied one-to-one)

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

**Comment by Neecolaa** [comment]
@fyliu since we're replacing this event table with the one in #173, should we close this issue?

**Comment by fyliu** [comment]
@Neecolaa I agree. Closing issue.
