### ISSUE TITLE
Create Table: event_history

### ISSUE THREAD

**Issue by ericvennemeyer** [hackforla/peopledepot#49]
### Overview

We need to create the event_history table so that we can update a shared data store across hackforla.org, vrms, civictechjobs, and tables (onboarding) project.

#### Details

A table and a model are the same thing

### Action Items

- [ ] decide if we're using django-simple-history for this table
  - [ ] release #37 from ice box
  - [ ] release #67 from ice box
- [x] identify and document table description (see spreadsheet under Resources)
  - [x] if not, reach out to PD leads
- [x] compare and check off the data fields (below) against the ERD. Note any fields in the ERD that's missing from the list. (see Resources)
- [x] compare the check off associated tables (below) against the ERD. Note any associated tables in the ERD that's missing from the list (see Resources)
- [ ] create a single model in Django (defining schema)
- [ ] write a test for the relationships this model will have with other models (e.g., creating a user and assigning them a set of permissions on a project).
- [ ] write an API end point
- [ ] write API unit tests
- [ ] document the endpoint

### Resources/Instructions

- See [People Depot Resources wiki page](https://github.com/hackforla/peopledepot/wiki/Resources-and-Links) for links
  - ERD
  - Table and Field Definitions
  - API Endpoint
- See the [wiki page](https://github.com/hackforla/peopledepot/wiki/Create-Table-issues-data-gathering-workflow) for instructions.

### Description

A history of events

### Data Fields

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)

    - [x] (PK) id - int - Record Id
    - [ ] (FK) event_id - int - Record Id
    - [x] (FK) project_id - int - Record Id
    - [x] description - varchar
    - [x] video_conference_url - url varchar
    - [x] (FK) location_id - int - Record Id
    - [x] alt_location_name - varchar
    - [x] alt_address1 - varchar
    - [x] alt_address2 - varchar
    - [x] alt_location_city - varchar
    - [x] alt_location_state - varchar(2)
    - [x] alt_location_zip - varchar
    - [x] start_date_time - timestamp
    - [x] duration_in_min - int
    - [x] (FK) recurring_event_id - int - Record Id
    - [x] created - timestamp
    - [x] check_in_ready - boolean

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

### Associated Tables

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)
   - [x] location (many-to-one)
   - [x] project (many-to-one)
   - [x] recurring_event (many-to-one)
   - [x] event (implied one-to-one)

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

**Comment by ExperimentsInHonesty** [comment]
@Neecolaa will create a requirements for this so fang can evaluate the plug in

**Comment by fyliu** [comment]
[django-simple-history](https://github.com/jazzband/django-simple-history) is the plug-in Django app

**Comment by fyliu** [comment]
@brdeleon this issue is not ready for backend to work on yet. Please find one that has the smiley emoji in the title.

You can tell if it's ready for backend by looking at the "role: ..." tag in the issue. I see there's only one ready issue left. I'll check the board to see if more issues are ready to work on.

**Comment by fyliu** [comment]
This table is being removed in the new event schema design
- #88

So we should move any unfinished tasks into new issues:
- [ ] create issue to evaluate django-simple-history plugin for history models

**Comment by fyliu** [comment]
Closing this since there's nothing more to do.
