### ISSUE TITLE
Create Table: faq

### ISSUE THREAD

**Issue by ericvennemeyer** [hackforla/peopledepot#51]
### Overview

We need to create the faq table so that we can update a shared data store across hackforla.org, vrms, civictechjobs, and tables (onboarding) project.

#### Details

A table and a model are the same thing

### Action Items

- [x] identify and document table description (see spreadsheet under Resources)
  - [x] if not, reach out to PD leads
- [x] compare and check off the data fields (below) against the ERD. Note any fields in the ERD that's missing from the list. (see Resources)
- [x] compare the check off associated tables (below) against the ERD. Note any associated tables in the ERD that's missing from the list (see Resources)
- [x] create a single model in Django (defining schema)
- [ ] write a test for the relationships this model will have with other models (e.g., creating a user and assigning them a set of permissions on a project).
- [x] write an API end point
- [x] write API unit tests
- [ ] document the endpoint

### Resources/Instructions

- See [People Depot Resources wiki page](https://github.com/hackforla/peopledepot/wiki/Resources-and-Links) for links
  - ERD
  - Table and Field Definitions
  - API Endpoint
- See the [wiki page](https://github.com/hackforla/peopledepot/wiki/Create-Table-issues-data-gathering-workflow) for instructions.

### Description

List of FAQs

### Data Fields

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)

    - [x] (PK) id - int
    - [x] question - varchar
    - [x] answer - varchar
    - [x] tool_tip_name - varchar
    - [x] created - timestamp
    - [x] updated - timestamp
    

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

### Associated Tables

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)
      - [x] faq_viewed (one-to-many)

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

**Comment by AzaniaBG** [comment]
ETA: 09/24/2022 by 5 PM
Availability: 09/22/2022 7 AM - 10 AM, 09/23/2022 7 AM - 9 AM, 09/24/2022 7 AM - 9 AM

**Comment by fyliu** [comment]
Manually closing this. The last PR says it's already been merged.
