### ISSUE TITLE
Remove Table: frequency from ERD and sheet

### ISSUE THREAD

**Issue by ericvennemeyer** [hackforla/peopledepot#53]
### Overview

We need to create the frequency table so that we can update a shared data store across hackforla.org, vrms, civictechjobs, and tables (onboarding) project.

#### Details

A table and a model are the same thing

### Action Items

- [x] identify and document table description (see spreadsheet under Resources)
  - [x] if not, reach out to PD leads
- [x] compare and check off the data fields (below) against the ERD. Note any fields in the ERD that's missing from the list. (see Resources)
- [x] compare the check off associated tables (below) against the ERD. Note any associated tables in the ERD that's missing from the list (see Resources)
- [ ] create a single model in Django (defining schema)
- [ ] add seed data
- [ ] write a test for the relationships this model will have with other models (e.g., creating a user and assigning them a set of permissions on a project).
- [ ] write an API end point
- [ ] write API unit tests
- [ ] document the endpoint

### Resources/Instructions

- See [People Depot Resources wiki page](https://github.com/hackforla/peopledepot/wiki/Resources-and-Links) for links
  - ERD
  - Table and Field Definitions
  - API Endpoint
- See the [wiki page](https://github.com/hackforla/peopledepot/wiki/Create-Table-issues-data-gathering-workflow) for instructions.

### Description

How often an event recurs

### Data Fields

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)

    - [x] (PK) id - int
    - [x] name - varchar
    - [x] description - varchar

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

### Associated Tables

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)
      - [x] recurring_event (one-to-many)

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

**Comment by fyliu** [comment]
@joshuayhwu This is pretty good. Now I realize the add table guide is missing some things.
We use `uuid` instead of `id` as the primary key. It's provided by the AbstractBaseModel so you don't need to declare it.
`description` should be TextField and no max_length but has blank=True to make it optional.

I'll add these to the documentation soon. It's supposed to be more or less usable by people with little or no experience with django. I just need to figure out what people need.

**Comment by cnk** [comment]
@fyliu I don't think you want a Frequency table for your recurring events. I think this should use a recurrence rule inside the RecurringEvent model. For a tutorial on what I mean, please see https://www.nylas.com/blog/calendar-events-rrules/ The python dateutil module has what looks to be fairly decent support for recurrence rules following the generally accepted standards. To use this in Django, I suggest this package: https://django-recurrence.readthedocs.io/en/latest/usage/api.html

**Comment by fyliu** [comment]
@cnk yup. I created an issue to redo the table using the iCalendar standard rrule and other fields.
- #88

**Comment by fyliu** [comment]
@joshuayhwu sorry to do this but I need to move this issue into the icebox since it might need to be replaced.

**Comment by ExperimentsInHonesty** [comment]
Task

- [ ] Remove from ERD - we are going to use django-recurrence see issue #88 
- [ ] Close the issue

**Comment by Neecolaa** [comment]
- [ ] Remove from ERD
- [ ] Remove from Spreadsheet
   - [ ] fields tab
   - [ ] tables tab
   - [ ] data tab (if exists)
- [ ] Remove/strikethrough from associated table issues
   - [ ] recurring_event

**Comment by Neecolaa** [comment]
Table has been removed from schema documents. Since it was not yet implemented, it's effectively removed.
