### ISSUE TITLE
Create Table: language :smile: 

### ISSUE THREAD

**Issue by ericvennemeyer** [hackforla/peopledepot#54]
### Overview

We need to create the language table so that we can update a shared data store across hackforla.org, vrms, civictechjobs, and tables (onboarding) project.

#### Details

A table and a model are the same thing

### Action Items

- [x] identify and document table description (see spreadsheet under Resources)
  - [x] if not, reach out to PD leads
- [x] compare and check off the data fields (below) against the ERD. Note any fields in the ERD that's missing from the list. (see Resources)
- [x] create a single model in Django (defining schema)
- [x] compare the check off associated tables (below) against the ERD. Note any associated tables in the ERD that's missing from the list (see Resources)
- [ ] write a test for the relationships this model will have with other models (e.g., creating a user and assigning them a set of permissions on a project).
- [x] write an API end point
- [x] write API unit tests
- [x] document the endpoint
- [x] Release #64 from ice box

### Resources/Instructions

- See [People Depot Resources wiki page](https://github.com/hackforla/peopledepot/wiki/Resources-and-Links) for links
  - ERD
  - Table and Field Definitions
  - API Endpoint
- See the [wiki page](https://github.com/hackforla/peopledepot/wiki/Create-Table-issues-data-gathering-workflow) for instructions.

### Description

Dictionary of languages

### Data Fields

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)

    - [x] (PK) id - int - Record Id
    - [x] name - varchar
    - [x] description - textfield
    - [x] logo - url varchar
    - [x] updated - varchar

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - [ ] logo - URLField

### Associated Tables

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)
      - [x] project_language_xref (one-to-many)

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

**Comment by scarter31191** [comment]
@scarter31191@gmail.com

**Comment by chelseybeck** [comment]
There is a way to do this that pulls in a list w/ IANA registry. See [django-language-field](https://pypi.org/project/django-language-field/)

**Comment by fyliu** [comment]
Updated description field to be textfield in django.

**Comment by AzaniaBG** [comment]
ETA: not sure, but I'm shooting for next Thursday, 7/13 (will update if needed).
Availability: 
- Saturday: 6 AM - 9 AM
- Sunday: 11 AM - 2 PM

**Comment by AzaniaBG** [comment]
Update: I didn't have a chance to work on this last week. 
New ETA: 7/20/23. 
Availability: 
Saturday 7/15 7 AM - 10 AM
Sunday 7/16 7 AM - 10 AM

**Comment by AzaniaBG** [comment]
Description field [here](https://docs.google.com/spreadsheets/d/1x_zZ8JLS2hO-zG0jUocOJmX16jh-DF5dccrd_OEGNZ0/edit#gid=1572339087), Cell H73 does not match - Fang updated ([per comment](https://github.com/hackforla/peopledepot/issues/54#issuecomment-1556040129) in May). Do we need to update the data field type in the [tables](https://docs.google.com/spreadsheets/d/1x_zZ8JLS2hO-zG0jUocOJmX16jh-DF5dccrd_OEGNZ0/edit#gid=1572339087) spreadsheet?

**Comment by fyliu** [comment]
Tagging Nicole for Question 1.

@Neecolaa remember we decided to make all the description fields TextFields in Django. They're varchar in the DB spreadsheet and ERD. Do we need to update the documents to say something like text instead of varchar?

For question 2, I'm not sure there's a problem. The DJANGO_SUPERUSER variables are in the current `.env.dev-sample` file. I think they just need to be copied to your `.env.dev`. It's a new addition since you last worked on this project. The `--no-input` flag should work after the variables are there.

**Comment by AzaniaBG** [comment]
@fyliu ~ thank you, I think you answered my second question. Please let me know what you decide for my [other question](https://github.com/hackforla/peopledepot/issues/54#issuecomment-1637157329): Do we need to update the data field type in the [tables spreadsheet](https://docs.google.com/spreadsheets/d/1x_zZ8JLS2hO-zG0jUocOJmX16jh-DF5dccrd_OEGNZ0/edit#gid=1572339087) and/or ERD?

Update: this issue should be resolved by next Thursday.
Availability:
Saturday 7/15 7 AM - 10 AM
Sunday 7/16 7 AM - 10 AM

**Comment by AzaniaBG** [comment]
Update:
Got the project running and reviewed [this how-to](https://github.com/hackforla/peopledepot/blob/main/docs/how-to/add-model-and-api-endpoints.md) documentation for adding new model and API endpoints.
This issue should be resolved by next Thursday (8/3).
Availability:
Friday 8/28 6 AM - 7 AM
Saturday 7/16 7 AM - 11 AM

**Comment by AzaniaBG** [comment]
Update:
I'm having some issues with the repo. It seems to be forked from the `fyliu` repo instead of the `/hackforla/peopledepot` repo.
Everything is complete, but I have a question on the `id` and `updated_on` Model fields. I should probably work on the `project_language_xref` table next.

**Comment by AzaniaBG** [comment]
Update: I submitted a PR for this issue and moved it to "New Issue Review." I posted in the Slack channel asking if this is the correct process once a PR has been submitted. I can work on the corresponding table next.
**Availability for week of 8/20:**
Wednesday: 6 AM - 7 AM
Thursday: 6 AM - 7 AM
Sunday 7 AM - 11 AM

**Comment by AzaniaBG** [comment]
Update: I addressed the changes requested. This issue should be complete after Fang reviews/approves the PR. I can then start working on the related issue.
**Availability for next week** (week of 8/27):
Thursday and Friday: 6 - 7 AM
Saturday: 7 - 11 AM

**Comment by AzaniaBG** [comment]
This PR has been merged and I picked up the corresponding issue (#64).

**Comment by AzaniaBG** [comment]
@fyliu @chelseybeck ~ does the Project Manager move this to done? I still have one sub-task to complete that links to the other table.

**Comment by chelseybeck** [comment]
@AzaniaBG - you can mark it as done once all tasks are complete.

**Comment by AzaniaBG** [comment]
@fyliu ~ I thought this issue was merged, but I don't see it in the HfLA repo.

**Comment by fyliu** [comment]
@AzaniaBG looks like the PR was closed today without merging. I'll go fix it. Thanks!
