### ISSUE TITLE
Eliminate event/event_history tables location redundancies

### ISSUE THREAD

**Issue by fyliu** [hackforla/peopledepot#55]
### Dependency
- might be made irrelevant by #88 . We should revisit this when that's done.

### Overview

As database designers, one of our goals to eliminate data redundancy. The event and event_history tables contain redundancies which should be eliminated.

### Action Items

- [ ] replace the alt_location fields in event and event_history tables with an alt_location_id FK reference to location table
- [ ] remove location_id FK reference in event table
- [ ] change duplicate fields in event and event_history that are already in recurring_event into alt_ fields
- [ ] potentially redesign the event/recurring_event tables to fit better in to a relational db

### Resources/Instructions
See the page involving normalization and First Normal Form [here](https://www.relationaldbdesign.com/database-analysis/module3/achieving-first-normal.php).

alt_location_name, alt_address_1, alt_address_2, alt... in the event and event_history tables are redundant since they also exist in the location table. To eliminate the redundancy, we can replace all those fields by an alt_location_id FK reference to the location table.

Also, the existing location_id in event table is redundant and should be removed, since it references recurring_event, which also contains the regular event location. The alt_location in event table is meant to be an override for the single event in case the regular venue is unavailable.

In fact, any event field that exists in recurring_event should be an alt_ field. They don't come into play except to override the regular event data from the recurring event.

**Comment by Neecolaa** [comment]
I agree that alt_location_id makes more sense than all of the alt location fields.

For location_id in event/event_history: 

- Do we care about historical data for event locations? Does it matter that Event A regularly took place at Location B but moved to Location C in 2022? That's the only case I can think of for keeping the location_id in event and event_history records, since recurring_event only holds future repeating events.

- I assume for one-off events we could store the location in alt_location_id and that would be fine.

**Comment by fyliu** [comment]
That makes sense to copy the location_id over to each event and event_history for historical record in case the recurring_event location gets updated at some point. It wouldn't be duplicating data.

~~Now I also understand copying the video_conference_url, location_id, and meeting times from recurring_event to event.~~

~~And we don't need a recurring_event_history table because projects can keep updating the same recurring_event record and new events can be created from that. For old events in event_history, maybe the links to the recurring_events records don't need to match the state they were at the times of the events?~~

I'm trying lay out what the design could be and the pros/cons of them

**Copy relevant data from recurring_event to each actual event**
1. YES, have the event record copy the relevant "data" from recurring_event to keep track of meeting history.
   1. easy to use. no need to follow the recurring_event reference to get the data
   1. duplicate data. things like location_id, project_id, video_conference_url, etc. will get copied, costing disk space and indirectly affect db performance? This might not be bad if really old events can be archived and removed from the active db.
1. NO, leave the data in recurring_event and treat any data in the event record as an override
   1. no duplicate data
   1. extra join. queries for event information will always require a join with recurring event, costing extra processing power
   1. create recurring_event record on change. relying on the join requires that any change to a recurring_event record will need to end that record and create a copy of it with a new start time at the time of the change. See discussion of handling recurring_event changes below

**Updating recurring_event record creates a new entry**
1. YES, any change to a recurring_event record will need to end that record and create a copy of it with a new start time at the time of the change.
   1. always up to date relationships. The event - recurring_event association is always up to date. No old event records referencing new recurring_events
   1. extra logic. This requires extra logic although it wouldn't happen very often.
   1. takes more space. Creating new records on change means recurring_event records could grow in numbers faster and may require an archive table for records we don't care about anymore.
1. NO, we allow recurring_event records to be updated
   1. save on space. no new records created. just the original record and no extra logic of creating records
   1. outdated relationships. When a recurring_event record changes, any previous event records that reference it is pointing at outdated information.

**Comment by fyliu** [comment]
I feel that the way that uses relations to access the data and not copying them is the correct way to do it. But I think it's not a quick thing to model out and we should leave the design as-is for now. Maybe we can look at other projects for ideas on how to organize these relationships and tables.

[django calendar apps](https://djangopackages.org/grids/g/calendar/) that might serve as references for ideas

**Comment by ExperimentsInHonesty** [comment]
Django plugin to create history tables

**Comment by fyliu** [comment]
- I think this is a problem pre-#88 but maybe I can't say whether or not it will still exist after. So I'm going to put this on hold to revisit after that's done.

**Comment by fyliu** [comment]
Closing this one since it's not in the redesign anymore.
