### ISSUE TITLE
Remove Table: day_of_week from ERD & sheet

### ISSUE THREAD

**Issue by ericvennemeyer** [hackforla/peopledepot#60]
### Overview

We need to create the day_of_week table so that we can update a shared data store across hackforla.org, vrms, civictechjobs, and tables (onboarding) project.

#### Details

A table and a model are the same thing

### Action Items

- [x] identify and document table description (see spreadsheet under Resources)
  - [x] if not, reach out to PD leads
- [x] compare and check off the data fields (below) against the ERD. Note any fields in the ERD that's missing from the list. (see Resources)
- [x] compare the check off associated tables (below) against the ERD. Note any associated tables in the ERD that's missing from the list (see Resources)
- [ ] create a single model in Django (defining schema)
- [ ] write a test for the relationships this model will have with other models (e.g., creating a user and assigning them a set of permissions on a project).
- [ ] write an API end point
- [ ] write API unit tests
- [ ] document the endpoint

#### Remove table actions
- [ ] Decide if we should remove this table
- [ ] Release #79 from ice box after applying any necessary updates to it
- [ ] Remove table from design files

### Resources/Instructions

- See [People Depot Resources wiki page](https://github.com/hackforla/peopledepot/wiki/Resources-and-Links) for links
  - ERD
  - Table and Field Definitions
  - API Endpoint
- See the [wiki page](https://github.com/hackforla/peopledepot/wiki/Create-Table-issues-data-gathering-workflow) for instructions.

### Description

N/A

### Data Fields

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)
   
    **No data fields found in spreadsheet!**

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - [ ] (PK) id - int
   - [ ] name - varchar
   - [ ] abbreviation - char(3)

### Associated Tables

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)
  - [x] user_availability (one-to-many)

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

**Comment by Neecolaa** [comment]
In the past we've discussed having day_of_week being an enum rather than its own table. Both PostgreSQL and django allow for enums. The one use of day_of_week in the spreadsheet (from recurring_event) has the description "enumerated field".

**Comment by joshuayhwu** [comment]
```
class Day_Of_Week(AbstractBaseModel):
	"""
	Day of Week
	"""
	id = models.IntegerField(primary_key=True)
	name = models.CharField(max_length=255)
	abbreviation = models.CharField(max_length=3)


	def __str__(self): 
		return f"{self.name}" 

```

**Comment by ExperimentsInHonesty** [comment]
Task

- [ ] Remove from ERD - we are going to use django-recurrence see issue #88 
- [ ] Close the issue

**Comment by Neecolaa** [comment]
Removed references to day_of_week table from _Tables_ and _Fields_ tabs in spreadsheet

**Comment by fyliu** [comment]
Just a quick comment. There's also [this package](https://pypi.org/project/django-weekday-field/) that's basically a toggle selection of 0 or more weekdays. I assume the goal of the user_availability is to select a number of weekdays.

Here's where it gets long:

But, on the other hand, this might not even be enough since it should probably be a weekdays+times-of-day selection. I'm not sure if there's an existing solution for this.

A lot of meeting coordinating services like lettucemeet have a "drag to select time range" UI. I think we want to have a backend that can store that data in a weekly sense. Or should it be something where the user selects times for each week separately, using actual dates rather than weekdays? This is actually the way it's done in apps I've seen. I think we should ask the stakeholders what they're planning to do and what they need.

**Comment by Neecolaa** [comment]
About #79 :
Currently, it's designed to hold a date and a time range (start and duration. I assume in hours, but we could do minutes), with the ability to store multiple time ranges for the same day of the week. We were thinking it'd be a more general "I'm free on Fridays from 5-10PM" vs a more specific date, but it would be a good idea to ask the stakeholders what they're going to actually use it for. Not sure if there's a current UI idea for how people would select their availability.

**Comment by fyliu** [comment]
You're right. I think a general same time each week is good too since it's how we do meeting schedule here.

After your clarification. I see that the enumeration type like you say would be more fitting.

**Comment by ExperimentsInHonesty** [comment]
- A decision was made in this issue to use an enumerated value instead of day of week table.  Action will need to be specified in issue #79.  Once that is done this issue can be closed.   We will do this at the next team meeting.

**Comment by PlantGirlCodes** [comment]
adding this item to next meeting agenda 9/21/23 breakout with fang & Nicole.

**Comment by Neecolaa** [comment]
We removed day_of_week table from the ERD and spreadsheet. We've given #79 a dependency on the event table so that we'll have a better idea of how we're dealing with the days of the week.
