### ISSUE TITLE
Create Table: practice_area

### ISSUE THREAD

**Issue by ericvennemeyer** [hackforla/peopledepot#63]
### Overview

We need to create the practice_area table so that we can update a shared data store across hackforla.org, vrms, civictechjobs, and tables (onboarding) project.

#### Details

A table and a model are the same thing

### Action Items

- [x] identify and document table description (see spreadsheet under Resources)
  - [x] if not, reach out to PD leads
- [x] compare and check off the data fields (below) against the ERD. Note any fields in the ERD that's missing from the list. (see Resources)
- [x] compare the check off associated tables (below) against the ERD. Note any associated tables in the ERD that's missing from the list (see Resources)
- [x] create a single model in Django (defining schema)
- [x] write a test for the relationships this model will have with other models (e.g., creating a user and assigning them a set of permissions on a project).
- [x] write an API end point
- [x] write API unit tests
- [ ] document the endpoint

### Resources/Instructions

- See [People Depot Resources wiki page](https://github.com/hackforla/peopledepot/wiki/Resources-and-Links) for links
  - ERD
  - Table and Field Definitions
  - API Endpoint
- See the [wiki page](https://github.com/hackforla/peopledepot/wiki/Create-Table-issues-data-gathering-workflow) for instructions.

### Description

Dictionary of practice areas

### Data Fields

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)

    - [x] (PK) id - int - Record Id
    - [x] name - varchar
    - [x] description - varchar

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - [ ] image - URLField
   - [ ] (FK) status_id - int

### Associated Tables

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)
   - [x] user (many-to-many array of ids)

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

**Comment by ExperimentsInHonesty** [comment]
@ethanstrominger I dont see any questions on this right now, so pushing back to in progress.  During todays meeting we will discuss how and where to put PRs on the board so that we don't miss them.

**Comment by Neecolaa** [comment]
Updated the relationships to reflect current schema. Doesn't cause changes to practice_area itself.
