### ISSUE TITLE
Create Table: project_language_xref

### ISSUE THREAD

**Issue by ericvennemeyer** [hackforla/peopledepot#64]
### Dependency

 - #54

### Overview

We need to create the project_language_xref table so that we can update a shared data store across hackforla.org, vrms, civictechjobs, and tables (onboarding) project.

#### Details

A table and a model are the same thing

### Action Items

- [x] identify and document table description (see spreadsheet under Resources)
  - [x] if not, reach out to PD leads
- [x] compare and check off the data fields (below) against the ERD. Note any fields in the ERD that's missing from the list. (see Resources)
- [x] compare the check off associated tables (below) against the ERD. Note any associated tables in the ERD that's missing from the list (see Resources)
- [ ] create a single model in Django (defining schema)
- [ ] write a test for the relationships this model will have with other models (e.g., creating a user and assigning them a set of permissions on a project).
- [ ] write an API end point
- [ ] write API unit tests
- [ ] document the endpoint

### Resources/Instructions

- See [People Depot Resources wiki page](https://github.com/hackforla/peopledepot/wiki/Resources-and-Links) for links
  - ERD
  - Table and Field Definitions
  - API Endpoint
- See the [wiki page](https://github.com/hackforla/peopledepot/wiki/Create-Table-issues-data-gathering-workflow) for instructions.

### Description

Join project to language

### Data Fields

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)

    - [x] (PK) id - int - Record Id
    - [x] (PK,FK) project_id - int - Record Id
    - [x] (PK,FK) language_id - int - Record Id
    - [x] created - timestamp
    - [x] ended - timestamp

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

### Associated Tables

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)
   - [x] language (many-to-one)
   - [x] project (many-to-one)

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

**Comment by fyliu** [comment]
This is better done after the language table since it references it.

**Comment by AzaniaBG** [comment]
The corresponding language issue is finished, so I moved this from the Ice Box.
Availability for this week:
Saturday 6 - 7 AM
Wednesday 6 - 7:45 AM
Thursday 6 - 7:45 AM

**Comment by AzaniaBG** [comment]
Update: I haven't been able to work on this issue (really busy with work). I'm hoping to have this finished by next Thursday.

Availability:
Friday (9/14): 6 - 7 AM
Saturday 7 - 10 AM
Wednesday: 6 - 7 AM
Thursday: 6 - 7 AM

**Comment by AzaniaBG** [comment]
Update: it doesn't look like the last issue, #54, was merged to the HfLA main repo. This should be merged before I start working on #64, per [Fang's comment](https://github.com/hackforla/peopledepot/issues/64#issuecomment-1556040358).

**Comment by AzaniaBG** [comment]
Unable to work on this as the Language table was not merged. Looks like this will be consolidated anyway - see #202.

**Comment by AzaniaBG** [comment]
I'm waiting to hear back on what the new xref table will be (this issue may go away, per issue #202).

**Comment by AzaniaBG** [comment]
I put moved this issue to the ice box, per discussion with @Neecolaa.

**Comment by Neecolaa** [comment]
- This is being replaced by #205
