### ISSUE TITLE
Create Table: project_sponsor_partner_xref

### ISSUE THREAD

**Issue by ericvennemeyer** [hackforla/peopledepot#65]
### Overview

We need to create the project_sponsor_partner_xref table so that we can update a shared data store across hackforla.org, vrms, civictechjobs, and tables (onboarding) project.

#### Details

A table and a model are the same thing

### Action Items

- [x] identify and document table description (see spreadsheet under Resources)
  - [x] if not, reach out to PD leads
- [x] compare and check off the data fields (below) against the ERD. Note any fields in the ERD that's missing from the list. (see Resources)
- [x] compare the check off associated tables (below) against the ERD. Note any associated tables in the ERD that's missing from the list (see Resources)
- [x] create a single model in Django (defining schema)
  - [x] add the docstring from the section below
- [x] write a test for the relationships this model will have with other models (e.g., creating a user and assigning them a set of permissions on a project).
- [x] write an API end point
- [x] write API unit tests
- [ ] document the endpoint

### After Merge

- [ ] Release #182 from the ice box if this is the last dependency

### Resources/Instructions

- See [People Depot Resources wiki page](https://github.com/hackforla/peopledepot/wiki/Resources-and-Links) for links
  - ERD
  - Table and Field Definitions
  - API Endpoint
- See the [wiki page](https://github.com/hackforla/peopledepot/wiki/Create-Table-issues-data-gathering-workflow) for instructions.

### Sponsor/Partner clarification

Sponsor/partner relationships stored in this table are project-dependent. They cannot be both a sponsor and a partner for the same project, so if is_sponsor is FALSE they are a project partner, if is_sponsor is TRUE they are a project sponsor.

### Description

Stores the relationship between sponsors/partners and projects (Joins tables sponsor_partner and project)

### Table name vs Model name

- [ ] The table name should be `project_affiliate_xref`, but the Django model name should be `Affiliation` for ease of coding.
  - [ ] Use `db_table` field in meta to specify the db table name

### Data Fields

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)

    - [x] (PK) id - int - Record Id
    - [x] (FK) project_id - int - id of project linked to partner
    - [x] (FK) partner_id - int - id of partner linked to project
    - [x] created - timestamp
    - [x] ended - timestamp
    - [x] is_sponsor - boolean
    - [x] is_partner - boolean

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

### Associated Tables

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)
   - [x] project (many-to-one)
   - [x] sponsor_partner (many-to-one)

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

**Comment by Neecolaa** [comment]
This table should not have the is_sponsor field. If we want to know if the linked relationship is with a sponsor or a partner, we can access that via the sponsor_partner table.

**Comment by fyliu** [comment]
I think I want some clarification from the stakeholder. Maybe there's a case where a sponsor is sponsoring only a project.

Question for stakeholder:

1. Are there different/separate levels of partners like
   - project partner
   - project sponsor
   - brigade partner
   - brigade sponsor
   - brigade partner project sponsor
   - brigade sponsor project sponsor
   - other combinations...

**Comment by Neecolaa** [comment]
I agree that if the sponsor/parter distinction is project-dependent, then is_sponsor would belong in this table and be removed from the sponsor_parter table instead.

**Comment by ExperimentsInHonesty** [comment]
@Neecolaa will review the comments in the issue and update the instructions above and hide any comments that won't need to be read again.

**Comment by fyliu** [comment]
I made it so that Nicole's clarification of the sponsor/partner will become part of the django model's docstring.

I'm not sure if it's better to put it in the model or in the API. My thinking right now is to put it closer to the database, which means the model. We might want to move or put a copy in the API since that's what the API client reads.

**Comment by fyliu** [comment]
On second thought, it'd be better to figure out the documentation guidelines in a separate issue. I created #182 for this. I'll hide this and the last comment since they don't contribute to this issue.

**Comment by Neecolaa** [comment]
renamed this table to maintain the xref naming convention (table_a_table_b_xref). Updates also made to the spreadsheet and ERD

**Comment by fyliu** [comment]
@freaky4wrld I think it's the clarification section.

**Comment by fyliu** [comment]
@Neecolaa I brought up converting the boolean `is_partner` into an enum or choice. [Here's the django documentation](https://docs.djangoproject.com/en/4.2/ref/models/fields/#enumeration-types) on that. It'd be a char field in the database.

To add choices, we'd have to modify the code. It shouldn't need to modify the database, since it'd still be a char field. However, it's not something that could be added on the fly like `stack_element_type`.

**Comment by Neecolaa** [comment]
I've updated this issue with a new field: `is_partner`
The ERD has also been updated, but the spreadsheet still needs to be updated as well.
