### ISSUE TITLE
Create Table: sponsor_partner

### ISSUE THREAD

**Issue by fyliu** [hackforla/peopledepot#76]
### Overview

We need to create the sponsor_partner table so that we can update a shared data store across hackforla.org, vrms, civictechjobs, and tables (onboarding) project.

#### Details

A table and a model are the same thing

### Action Items

- [ ] identify and document table description (see spreadsheet under Resources)
  - [ ] if not, reach out to PD leads
- [ ] compare and check off the data fields (below) against the ERD. Note any fields in the ERD that's missing from the list. (see Resources)
- [ ] compare the check off associated tables (below) against the ERD. Note any associated tables in the ERD that's missing from the list (see Resources)
- [x] create a single model in Django (defining schema)
- [ ] write a test for the relationships this model will have with other models (e.g., creating a user and assigning them a set of permissions on a project).
- [x] write an API end point
- [ ] write API unit tests
- [ ] document the endpoint

### Resources/Instructions

- See [People Depot Resources wiki page](https://github.com/hackforla/peopledepot/wiki/Resources-and-Links) for links
  - ERD
  - Table and Field Definitions
  - API Endpoint
- See the [wiki page](https://github.com/hackforla/peopledepot/wiki/Create-Table-issues-data-gathering-workflow) for instructions.

### Description

Dictionary of sponsors and partners

### Data Fields

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)
   - [ ] (PK) id - int - Record Id
   - [x] partner_name - varchar()
   - [x] partner_logo - urlString
   - [x] is_active - boolean
   - [x] url - url varchar
   - [x] is_sponsor - boolean

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

### Associated Tables

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)
   - [ ] project_partner_xref (one-to-many)

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

**Comment by Neecolaa** [comment]
Because we can have project level sponsors and partners that are not org-level sponsors/partners, we are going to remove the is_sponsor boolean and replace it with both an is_org_sponsor boolean and an is_org_partner boolean. Discussion about this is also here: https://github.com/hackforla/peopledepot/issues/65#issuecomment-1563579917
