### ISSUE TITLE
Separate Phone model from User

### ISSUE THREAD

**Issue by fyliu** [hackforla/peopledepot#89]
### Overview
Suggestion from a PR review. The phone and texting_ok fields should be separated into its own model that relates to the user.

### Action Items
- [ ] discussion
- [ ] decision and reasoning
- [ ] add a decision record 

### Discussion Items
- [ ] current design
- [ ] proposed design
- [ ] advantages/disadvantages

### Resources/Instructions
- original comment

>Does this belong in the user model? I think we might want to model this as a Phone model (which has the ok_to_text field) with a ForeignKey to the user (and a unique_together = ['user', 'phone_number']

   _Originally posted by @cnk in https://github.com/hackforla/peopledepot/pull/83#discussion_r985360433_
      
- current design
  - everything in one table, no need to look up
- separate phone model
  - cleaner design with phone-related attribute in that model and user-related fields in user model
  - possiblity to associate multiple phone numbers with a user if we make it one to many. This would require an additional phone_type field

**Comment by ExperimentsInHonesty** [comment]
@fyliu I think we need to look up GDPR rules and try to think ahead to make our people depot and its clients (vrms, civic tech jobs, etc.) that take in and allow for editing of data to meet those standards.  I think that will end up dictating how we structure the whole thing.  Please talk to @Neecolaa about this.

**Comment by Neecolaa** [comment]
@cnk Since a user isn't going to have more than one phone number, having both `phone` and `texting_ok` as field's in user should be fine. "Is it ok to text Sarah?" is a question about the user Sarah, rather than her phone number.

**Comment by fyliu** [comment]
Closing this: as discussed during a meeting with @ExperimentsInHonesty and @Neecolaa and commented by @Neecolaa, the current structure is what best fits our needs.
