### ISSUE TITLE
How is faq_viewed meant to be used?

### ISSUE THREAD

**Issue by fyliu** [hackforla/peopledepot#93]
### Overview
As backend developers, we are having trouble understanding the design of the faq_viewed table. It looks like a normal junction table to relate faqs and projects, but the table name suggests that its role is the viewing of faqs, so this is confusing. See below on discussions of possible ways to use it.

### Action Items

- [x] come up with guesses at how it's meant to be used. See Discussion below
- [x] ask Bonnie what the intended use is

### Discussion

1. faq_viewed is **storing individual views** of the faq, but **not the faq_project associations**
   1. We start with a global faqs list with no project associations. **Doesn't seem right. Faqs should be associated with projects**
   1. A user that's associated with a project and a global faqs page. The user clicks on the + sign next to an faq entry and the app creates a new record of the faq + project + read timestamp.
1. faq_viewed is a **junction table that relates faqs and projects**
   1. We create an faq and set it to associate with a project. It contains an faq_viewed record without a read timestamp. But **why have the unused timestamp field**?
   1. An admin looking at the project's faqs list decides that an entry also applies to another project, and performs the necessary actions to create a new faq_viewed record, associating the faq to another project
   1. Another admin looking at the project's faqs list decides that an entry does not apply to the project, and performs the necessary actions to delete the faq_viewed record, breaking the association, but leaving any other associations or leaving the faq with no associated project.
   2. **But how is it using the read timestamp?**
1. faq_viewed is meant to **do both**
   1. We create an faq and set it to associate with a project. It contains an faq_viewed record without a read timestamp. **Extra unused read field**
   1. A user browsing the project's faqs list clicks on the + sign next to an faq entry and the app creates a new faq_viewed record, this time with a read timestamp.
   1. An admin looking at the project's faqs list decides that an entry does not apply to the project, and performs the necessary actions to delete the faq_viewed records, breaking the association, but leaving any other associations or leaving the faq with no associated project. In this case, multiple records may require deletion. **Duplicate data**

- Case 3 would make the most sense, but a slight redesign would make it work better.
   1. have an **faq_project junction table**. This fits the initial faq creation since it doesn't need to have the extra read timestamp
   1. either have a **read counter in that table** (for simple aggregate count) or have a **separate table to store individual read instances** (if we want to query for things like most read in the last week, month, year, etc)

**Comment by fyliu** [comment]
- This is from #52 that @AzaniaBG is working on. I had trouble explaining how it's supposed to work based on the [ERD](https://lucid.app/lucidchart/ac2f3e81-00d2-4257-b1fc-266d7f0a4cbe/view?page=0_0#).

**Comment by ExperimentsInHonesty** [comment]
I am not sure where the idea of associating FAQs with projects came about, but it's never been a requirement or for that matter even discussed.  Projects already have a way to curate data about their project that is not VRMS functionality specific, and that is their wiki.  Project leads being able to use the People Depo for FAQs would be a future version of people depot, not MVP

**Comment by fyliu** [comment]
The faq-project relationship is what @azania and I inferred based on the ERD, where faq_viewed contains a reference to faq and a reference to project. If this is not right, I think we need to clarify how faq_viewed actually makes use of the project_id field so that @AzaniaBG can implement it correctly. ![image](https://user-images.githubusercontent.com/1160105/194719590-46ca9b0b-53b9-4b10-9681-1d49d60d3b86.jpeg)

**Comment by AzaniaBG** [comment]
> I am not sure where the idea of associating FAQs with projects came about, but it's never been a requirement or for that matter even discussed. Projects already have a way to curate data about their project that is not VRMS functionality specific, and that is their wiki. Project leads being able to use the People Depo for FAQs would be a future version of people depot, not MVP

@ExperimentsInHonesty ~ We are not directly associating FAQs with projects, but the faq_viewed table shows a relation to FAQs (`faq_id` Foreign Key) and Projects (`project_id` Foreign Key). So the question is, when we're testing the faq_viewed model, how should we test it? Does faq_viewed relate to an FAQ that is not associated with a project (and vice versa)? Or do we want to be able to associate an FAQ to a specific project?

**Comment by Neecolaa** [comment]
Removing project_id from faq_viewed table, there's no current plan to have individualized FAQs for projects

To-do:
- [ ] remove column from ERD
- [ ] remove column from spreadsheet
- [ ] remove relationship between project and faq_viewed from spreadsheet

**Comment by Neecolaa** [comment]
Do we want to keep track of when the question was viewed, or just how often? If the view count is the only thing that matters, it makes more sense to have one record per faq that functions as a counter that keeps the number of times that faq question was viewed rather than multiple records holding the timestamps.

In fact, we could get rid of faq_viewed as a model, and instead add a `times_viewed` field to the faq model/table to hold how often that question was looked at.

**Comment by AzaniaBG** [comment]
> Do we want to keep track of when the question was viewed, or just how often? If the view count is the only thing that matters, it makes more sense to have one record per faq that functions as a counter that keeps the number of times that faq question was viewed rather than multiple records holding the timestamps.
> 
> In fact, we could get rid of faq_viewed as a model, and instead add a `times_viewed` field to the faq model/table to hold how often that question was looked at.

Makes sense to me @Neecolaa. Should I implement this or hold off until we confirm with Bonnie or Cynthia?

**Comment by ExperimentsInHonesty** [comment]
well the advantage of knowing when as well as how often, is that if you make a change to the website, and people access the question less after the site change, it will be hard to know that.

**Comment by AzaniaBG** [comment]
i could create the faq_viewed table as updated in the [ERD](https://lucid.app/lucidchart/ac2f3e81-00d2-4257-b1fc-266d7f0a4cbe/view?page=0_0#); it's not a heavy lift :)

**Comment by AzaniaBG** [comment]
@ExperimentsInHonesty ~ Questions for today's All-Team meeting based on review of [CTI's back end code](https://github.com/civictechindex/CTI-website-backend/tree/main/civictechindexadmin/data) for its FAQ model and [ViewSet](https://github.com/civictechindex/CTI-website-backend/blob/main/civictechindexadmin/data/api/views.py):
1. Should the faq model have a `count` field that tracks the number of times an FAQ is viewed, as CTI does (and as @Neecolaa suggested in this issue).
2. Should a new record on the faq_viewed table be created each time the link for a particular faq is clicked?
3. @cnk, Should the faq_viewed ViewSet define a fn that creates a new faq_viewed record that relates to the requested faq with the `read` field set to the date/time the faq endpoint was requested (e.g., `read = models.DateTimeField(auto_now_add=True`)?

**Comment by ExperimentsInHonesty** [comment]
@AzaniaBG @cnk  I am not sure how it works on the Civic Tech index.  Does it create a new record there each time, or does it just increment a counter in the database tied to the specific Q and Answer record?

**Comment by AzaniaBG** [comment]
> 

@ExperimentsInHonesty ~ it only increments a counter; there is no faq_viewed table. My understanding is that you would like the faq_viewed table to create a new record with the date/time a particular faq has been read. @cnk, I do not believe the faq table has a field that tracks each date/time a specified faq is read, but please correct me if I'm wrong about this.

**Comment by cnk** [comment]
Civic Tech Index is only using a [counter in the FAQ model](https://github.com/civictechindex/CTI-website-backend/blob/main/civictechindexadmin/data/models.py#L150). 

If you want to track when an FAQ is read, you will need the separate table proposed above (the far_viewed table) because this is a many to one relationship.

**Comment by fyliu** [comment]
We ended up implementing the model to track each view by creating a new row. The advantage is we can track when each faq was viewed and get read counts for different time frames. The disadvantage is there will be a lot more data rows this way. Eventually we may need to implement some kind of cleanup strategy to reclaim space, like delete rows older than x months, or combine counts per calendar month.
